# Generated by Django 4.2.7 on 2024-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name',), 'permissions': [('activate_delete_users', 'Can activate/delete users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
