# Generated by Django 4.2.7 on 2024-02-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение'),
        ),
    ]
