# Generated by Django 4.2.7 on 2024-03-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_promo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'permissions': [('set_promo_active_status', 'Can activate/deactivate promo')], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
