# Generated by Django 4.2.7 on 2024-03-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='slug',
        ),
    ]
