# Generated by Django 4.2.7 on 2024-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_remove_promo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
