# Generated by Django 4.2.7 on 2024-03-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_doctor'),
        ('main', '0004_doctorspeciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorSpeciality',
        ),
    ]
