# Generated by Django 4.2.7 on 2024-03-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_delete_doctorspeciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(verbose_name='Медицинское назначение')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализов',
                'ordering': ('-created_date',),
                'permissions': [('modify_medical_results', 'Can add/edit medical results')],
            },
        ),
        migrations.CreateModel(
            name='MedicalResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_results/')),
                ('medical_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.medicalresult')),
            ],
            options={
                'verbose_name': 'Файл результатов',
                'verbose_name_plural': 'Файлы результатов',
                'permissions': [('modify_medical_results', 'Can add/edit medical results')],
            },
        ),
    ]
