# Generated by Django 4.2.7 on 2024-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('activate_delete_users', 'Can activate/delete users')], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
    ]
